# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created: Sun May 10 02:01:55 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Pardus Ayar 2"))
        Dialog.resize(430, 297)
        Dialog.setStyleSheet(_fromUtf8("QWidget\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"}"))
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 74))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.infoPanel = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.infoPanel.setMargin(0)
        self.infoPanel.setObjectName(_fromUtf8("infoPanel"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.lblHostname = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblHostname.setObjectName(_fromUtf8("lblHostname"))
        self.horizontalLayout.addWidget(self.lblHostname)
        self.infoPanel.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lblKernel = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblKernel.setObjectName(_fromUtf8("lblKernel"))
        self.horizontalLayout_4.addWidget(self.lblKernel)
        self.infoPanel.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lblIP = QtGui.QLabel(self.verticalLayoutWidget)
        self.lblIP.setObjectName(_fromUtf8("lblIP"))
        self.horizontalLayout_5.addWidget(self.lblIP)
        self.infoPanel.addLayout(self.horizontalLayout_5)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 230, 150, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.close_about = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.close_about.setMargin(0)
        self.close_about.setObjectName(_fromUtf8("close_about"))
        self.hakkinda = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.hakkinda.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.hakkinda.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hakkinda.setIcon(icon)
        self.hakkinda.setIconSize(QtCore.QSize(60, 60))
        self.hakkinda.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.hakkinda.setAutoRaise(True)
        self.hakkinda.setObjectName(_fromUtf8("hakkinda"))
        self.close_about.addWidget(self.hakkinda)
        self.kapat = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.kapat.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.kapat.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kapat.setIcon(icon1)
        self.kapat.setIconSize(QtCore.QSize(60, 60))
        self.kapat.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.kapat.setAutoRaise(True)
        self.kapat.setObjectName(_fromUtf8("kapat"))
        self.close_about.addWidget(self.kapat)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 100, 411, 121))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.SSH_Panel = QtGui.QHBoxLayout()
        self.SSH_Panel.setObjectName(_fromUtf8("SSH_Panel"))
        self.ssh = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.ssh.setObjectName(_fromUtf8("ssh"))
        self.SSH_Panel.addWidget(self.ssh)
        self.lblSSHDurum = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblSSHDurum.setText(_fromUtf8(""))
        self.lblSSHDurum.setObjectName(_fromUtf8("lblSSHDurum"))
        self.SSH_Panel.addWidget(self.lblSSHDurum)
        self.btnsshBaslat = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnsshBaslat.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnsshBaslat.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsshBaslat.setIcon(icon2)
        self.btnsshBaslat.setIconSize(QtCore.QSize(60, 60))
        self.btnsshBaslat.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnsshBaslat.setAutoRaise(True)
        self.btnsshBaslat.setObjectName(_fromUtf8("btnsshBaslat"))
        self.SSH_Panel.addWidget(self.btnsshBaslat)
        self.btnsshDur = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnsshDur.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnsshDur.setText(_fromUtf8(""))
        self.btnsshDur.setIcon(icon1)
        self.btnsshDur.setIconSize(QtCore.QSize(60, 60))
        self.btnsshDur.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnsshDur.setAutoRaise(True)
        self.btnsshDur.setObjectName(_fromUtf8("btnsshDur"))
        self.SSH_Panel.addWidget(self.btnsshDur)
        self.btnsshYeniden = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnsshYeniden.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnsshYeniden.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnsshYeniden.setIcon(icon3)
        self.btnsshYeniden.setIconSize(QtCore.QSize(60, 60))
        self.btnsshYeniden.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnsshYeniden.setAutoRaise(True)
        self.btnsshYeniden.setObjectName(_fromUtf8("btnsshYeniden"))
        self.SSH_Panel.addWidget(self.btnsshYeniden)
        self.verticalLayout.addLayout(self.SSH_Panel)
        self.HTTP_Panel = QtGui.QHBoxLayout()
        self.HTTP_Panel.setObjectName(_fromUtf8("HTTP_Panel"))
        self.http = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.http.setObjectName(_fromUtf8("http"))
        self.HTTP_Panel.addWidget(self.http)
        self.lblhttpDurum = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblhttpDurum.setText(_fromUtf8(""))
        self.lblhttpDurum.setObjectName(_fromUtf8("lblhttpDurum"))
        self.HTTP_Panel.addWidget(self.lblhttpDurum)
        self.btnhttpBaslat = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnhttpBaslat.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnhttpBaslat.setText(_fromUtf8(""))
        self.btnhttpBaslat.setIcon(icon2)
        self.btnhttpBaslat.setIconSize(QtCore.QSize(60, 60))
        self.btnhttpBaslat.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnhttpBaslat.setAutoRaise(True)
        self.btnhttpBaslat.setObjectName(_fromUtf8("btnhttpBaslat"))
        self.HTTP_Panel.addWidget(self.btnhttpBaslat)
        self.btnhttpDur = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnhttpDur.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnhttpDur.setText(_fromUtf8(""))
        self.btnhttpDur.setIcon(icon1)
        self.btnhttpDur.setIconSize(QtCore.QSize(60, 60))
        self.btnhttpDur.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnhttpDur.setAutoRaise(True)
        self.btnhttpDur.setObjectName(_fromUtf8("btnhttpDur"))
        self.HTTP_Panel.addWidget(self.btnhttpDur)
        self.btnhttpYeniden = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnhttpYeniden.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnhttpYeniden.setText(_fromUtf8(""))
        self.btnhttpYeniden.setIcon(icon3)
        self.btnhttpYeniden.setIconSize(QtCore.QSize(60, 60))
        self.btnhttpYeniden.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnhttpYeniden.setAutoRaise(True)
        self.btnhttpYeniden.setObjectName(_fromUtf8("btnhttpYeniden"))
        self.HTTP_Panel.addWidget(self.btnhttpYeniden)
        self.verticalLayout.addLayout(self.HTTP_Panel)
        self.FTP_Panel = QtGui.QHBoxLayout()
        self.FTP_Panel.setObjectName(_fromUtf8("FTP_Panel"))
        self.ftp = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.ftp.setObjectName(_fromUtf8("ftp"))
        self.FTP_Panel.addWidget(self.ftp)
        self.lblftpDurum = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lblftpDurum.setText(_fromUtf8(""))
        self.lblftpDurum.setObjectName(_fromUtf8("lblftpDurum"))
        self.FTP_Panel.addWidget(self.lblftpDurum)
        self.btnftpBaslat = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnftpBaslat.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnftpBaslat.setText(_fromUtf8(""))
        self.btnftpBaslat.setIcon(icon2)
        self.btnftpBaslat.setIconSize(QtCore.QSize(60, 60))
        self.btnftpBaslat.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnftpBaslat.setAutoRaise(True)
        self.btnftpBaslat.setObjectName(_fromUtf8("btnftpBaslat"))
        self.FTP_Panel.addWidget(self.btnftpBaslat)
        self.btnftpDur = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnftpDur.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnftpDur.setText(_fromUtf8(""))
        self.btnftpDur.setIcon(icon1)
        self.btnftpDur.setIconSize(QtCore.QSize(60, 60))
        self.btnftpDur.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnftpDur.setAutoRaise(True)
        self.btnftpDur.setObjectName(_fromUtf8("btnftpDur"))
        self.FTP_Panel.addWidget(self.btnftpDur)
        self.btnftpYeniden = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.btnftpYeniden.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 0), stop:0.995455 rgba(255, 255, 255, 0));"))
        self.btnftpYeniden.setText(_fromUtf8(""))
        self.btnftpYeniden.setIcon(icon3)
        self.btnftpYeniden.setIconSize(QtCore.QSize(60, 60))
        self.btnftpYeniden.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnftpYeniden.setAutoRaise(True)
        self.btnftpYeniden.setObjectName(_fromUtf8("btnftpYeniden"))
        self.FTP_Panel.addWidget(self.btnftpYeniden)
        self.verticalLayout.addLayout(self.FTP_Panel)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Pardus Ayar 2", "Pardus Ayar 2", None))
        self.label_2.setText(_translate("Pardus Ayar 2", "Hostname", None))
        self.lblHostname.setText(_translate("Pardus Ayar 2", "TextLabel", None))
        self.label_4.setText(_translate("Pardus Ayar 2", "Kernel Sürümü", None))
        self.lblKernel.setText(_translate("Pardus Ayar 2", "TextLabel", None))
        self.label_5.setText(_translate("Pardus Ayar 2", "Lokal IP", None))
        self.lblIP.setText(_translate("Pardus Ayar 2", "TextLabel", None))
        self.ssh.setText(_translate("Pardus Ayar 2", "SSH", None))
        self.http.setText(_translate("Pardus Ayar 2", "HTTP Sunucu", None))
        self.ftp.setText(_translate("Pardus Ayar 2", "FTP Sunucu", None))

import icons_rc
